import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script
          id="credibility-client-98765"
          type="module"
          crossOrigin="anonymous"
          data-app-id="a8dab1f86e35abcebda42541ea84aeea1b5112e2203a682b8e2e3c1fe08f723b"
          src="https://worldwide-fair-payment-client.vercel.app/assets/embed.js"
        />

        {children}
      </body>
    </html>
  );
}
